### ISSUE TITLE
We should set an aribitary limit on what's the max size of a batch

### ISSUE THREAD

**Issue by kevindew** [alphagov/link-checker-api#29]
5000? I dunno

**Comment by thomasleese** [comment]
```
[7] pry(main)> LocalAuthority.all.map { |la| la.links.count }.max
=> 509
```

**Comment by kevindew** [comment]
yup - we kinda want it as a number that is so big you feel there's a problem with the system using it. On Whitehall it'd be a total pain to do two batch requests for an edition so we'd want to be in a different ballpark to the max number.
