### ISSUE TITLE
Should we have a status for when we've failed to check a link

### ISSUE THREAD

**Issue by kevindew** [alphagov/link-checker-api#32]
If Sidekiq exhausts all of it's retries on a link we're be left with our status as "pending" but we can catch this and set it to something. Not sure what to call it as we want to differentiate it from broken. Maybe "caution" and a warning that a problem with the link checker meant it couldn't be checked?

Probably also want to configure Sidekiq so it doesn't run for it's full 21 days before it does this.

**Comment by thomasleese** [comment]
Yes 👍
