### ISSUE TITLE
Undefined method body for LinkChecker::UriChecker::Report

### ISSUE THREAD

**Issue by kevindew** [alphagov/link-checker-api#54]
Just saw this error looks like it originates here: https://github.com/alphagov/link-checker-api/blob/master/lib/link_checker/uri_checker/http_checker.rb#L91 and is due to the link failing the request and a Report object being returned rather than a Response, code looks like it was anticipating a nil response in the case of a failure

**Comment by thomasleese** [comment]
Good catch, need to return `nil` at the end of `make_request` since `add_error` and `add_warning` return `self` to enable chaining.
